// Generated by https://quicktype.io

export interface ApiPoke {
  count:    number;
  next:     null;
  previous: null;
  results:  Result[];
}

export interface Result {
  name: string;
  url:  string;
}

export interface Pokemon{
  id:string;
  name:string;
  imagen:string;
}
